config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.FAIR:
    repos:
      this_repo:
        commands:
        - fair-eva.py --id http://hdl.handle.net/10261/157765 --plugin oai-pmh --repository
          http://digital.csic.es/dspace-oai/request
        container: qc.fair_tasty-aquamarine-chow
timeout: 5400
