services:
  qc.fair_wimpy-amber-eel:
    image: eoscsynergy/sqaaas-fair_eva:1.7.10-alpha2
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
