services:
  qc.fair_squeaky-cardinal-llama:
    image: eoscsynergy/sqaaas-fair_eva:1.7.10
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
