services:
  qc.fair_stealthy-cerise-burmese:
    image: eoscsynergy/sqaaas-fair_eva:1.7.10-alpha
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
