services:
  qc.fair_surly-ivory-booby:
    command: sleep 6000000
    image: eoscsynergy/sqaaas-fair_eva:1.7.11-alpha
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
