services:
  qc.fair_zippy-flax-angelfish:
    command: sleep 6000000
    image: eoscsynergy/sqaaas-fair_eva:2.0.0-alpha2
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
