services:
  qc.fair_cheeky-bistre-mastiff:
    command: sleep 6000000
    image: eoscsynergy/sqaaas-fair_eva:3.0.3
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
