services:
  qc.fair_lovely-mauve-kakapo:
    command: sleep 6000000
    image: eoscsynergy/sqaaas-fair_eva:2.0.0
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
